### ISSUE TITLE
Method to clean the list

### ISSUE THREAD

**Issue by DavisDev** [mellowcandle/liblist#10]
Is there a function that leaves a list empty?

**Comment by debanjan-basu** [comment]
A direct API does not exist. However an indirect use might be of using llist_for_each(...) and in the callback use llist_delete_node(...) for each node. I hope we would end up deleting all the the nodes from  one end of the linked list. o(n) time complexity, without deleting the existing structure llist. Would render the list empty I suppose

**Comment by mellowcandle** [comment]
You can use: llist_destroy() function to delete the entire list.
In need you can create a new one.
Perhaps we can implement llist_flush() function with destructor argument.
