### ISSUE TITLE
llist_find_node() not working on a list with a single entry

### ISSUE THREAD

**Issue by BenVella** [mellowcandle/liblist#15]
When running through list iterator it attempts to acquire the head element which returns as null on a single node list.
@ line 409:  `iterator = ((_llist *) list)->head;` return `NULL`

It also appears to fail to retrieve a found element (equal returns true) despite the element being valid as per below screenshot.

![image](https://user-images.githubusercontent.com/25787735/86257275-a0d6d880-bbb9-11ea-8a79-f58235f2bd5e.png)

**Comment by mellowcandle** [comment]
feel free to fix and send pull request.

**Comment by BenVella** [comment]
Disregard - this was due to an invalid found parameter being passed.  Closing issue
